/**
 * GetNewBlobKeyServlet.java
 * 
 * Description: Returns a blob key generated by Google's Blobstore Service.
 * 
 * File added: 12/18/2011	Pratik Mathur - Initial Import
 * 
 */

package edu.umd.cmsc798a.iremumcp.server.servlets;

import java.io.IOException;
import java.util.logging.Logger;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.appengine.api.blobstore.BlobstoreService;
import com.google.appengine.api.blobstore.BlobstoreServiceFactory;

public class GetNewBlobKeyServlet extends HttpServlet {

	private static final long serialVersionUID = -1480785941587796079L;
	
	private BlobstoreService blobstoreService = BlobstoreServiceFactory
	.getBlobstoreService();
	
	/**
	 * doGet - override function from HttpServlet
	 * @param req - accepts incoming request
	 * @param res - returns blob key in response
	 */
	public void doGet(HttpServletRequest req, HttpServletResponse res)
	throws IOException {
		Logger log = Logger.getLogger(GetNewBlobKeyServlet.class.getName());
		log.info("GetNewBlobKeyServlet.doGet()");
		String action_url = blobstoreService.createUploadUrl("/handleupload");
		String resOut = action_url.substring(action_url.lastIndexOf("upload/")+7, action_url.length()-1);
		System.out.println(resOut);
		res.getWriter().write(resOut);	
	}
}
